// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_AdminView_screen_init(void)
{
    ui_AdminView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AdminView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_AdminView, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AdminView, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_AdminView, &ui_img_loginback_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_AdminView);
    lv_obj_set_width(ui_Panel1, 579);
    lv_obj_set_height(ui_Panel1, 533);
    lv_obj_set_x(ui_Panel1, 4);
    lv_obj_set_y(ui_Panel1, 41);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserListHead = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_UserListHead);
    lv_obj_set_width(ui_UserListHead, 529);
    lv_obj_set_height(ui_UserListHead, 50);
    lv_obj_set_align(ui_UserListHead, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_UserListHead, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_UserListHead, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UserListHead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_UserListHead);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "用户名");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_UserListHead);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "用户类型");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_UserListHead);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "操作");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UserListBody = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_UserListBody);
    lv_obj_set_height(ui_UserListBody, 420);
    lv_obj_set_width(ui_UserListBody, lv_pct(100));
    lv_obj_set_x(ui_UserListBody, -1);
    lv_obj_set_y(ui_UserListBody, 32);
    lv_obj_set_align(ui_UserListBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_UserListBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_UserListBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_UserListItem = lv_obj_create(ui_UserListBody);
    lv_obj_remove_style_all(ui_UserListItem);
    lv_obj_set_width(ui_UserListItem, 531);
    lv_obj_set_height(ui_UserListItem, 50);
    lv_obj_set_x(ui_UserListItem, 0);
    lv_obj_set_y(ui_UserListItem, -2);
    lv_obj_set_align(ui_UserListItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_UserListItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_UserListItem, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_UserListItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_UserListItem);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "user");

    ui_Dropdown1 = lv_dropdown_create(ui_UserListItem);
    lv_dropdown_set_options(ui_Dropdown1, "普通客户\nVIP客户\n管理员");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &ui_font_harmonyOS,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_operation = lv_obj_create(ui_UserListItem);
    lv_obj_remove_style_all(ui_operation);
    lv_obj_set_width(ui_operation, 117);
    lv_obj_set_height(ui_operation, 50);
    lv_obj_set_align(ui_operation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_operation, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_operation, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_operation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_saveBtn = lv_btn_create(ui_operation);
    lv_obj_set_width(ui_saveBtn, 55);
    lv_obj_set_height(ui_saveBtn, 40);
    lv_obj_set_align(ui_saveBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_saveBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_saveBtn, lv_color_hex(0x82B7F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveBtnText = lv_label_create(ui_saveBtn);
    lv_obj_set_width(ui_saveBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_saveBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveBtnText, "保存");
    lv_obj_set_style_text_font(ui_saveBtnText, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userListUid = lv_label_create(ui_saveBtn);
    lv_obj_set_width(ui_userListUid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_userListUid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_userListUid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_userListUid, "1");
    lv_obj_add_flag(ui_userListUid, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_delBtn = lv_btn_create(ui_operation);
    lv_obj_set_width(ui_delBtn, 55);
    lv_obj_set_height(ui_delBtn, 40);
    lv_obj_set_align(ui_delBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_delBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_delBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_delBtn, lv_color_hex(0x82B7F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_delBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delBtnText = lv_label_create(ui_delBtn);
    lv_obj_set_width(ui_delBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_delBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delBtnText, "删除");
    lv_obj_set_style_text_font(ui_delBtnText, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delListUid = lv_label_create(ui_delBtn);
    lv_obj_set_width(ui_delListUid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delListUid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_delListUid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delListUid, "1");
    lv_obj_add_flag(ui_delListUid, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_OpenMeunBtn = lv_btn_create(ui_AdminView);
    lv_obj_set_width(ui_OpenMeunBtn, 115);
    lv_obj_set_height(ui_OpenMeunBtn, 36);
    lv_obj_set_x(ui_OpenMeunBtn, -416);
    lv_obj_set_y(ui_OpenMeunBtn, -267);
    lv_obj_set_align(ui_OpenMeunBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OpenMeunBtn, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_OpenMeunBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OpenMeunBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OpenMeunBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_OpenMeunBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_OpenMeunBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OpenMeunBtnText = lv_label_create(ui_OpenMeunBtn);
    lv_obj_set_width(ui_OpenMeunBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OpenMeunBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OpenMeunBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OpenMeunBtnText, "< 返回");
    lv_obj_set_style_text_color(ui_OpenMeunBtnText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OpenMeunBtnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OpenMeunBtnText, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OpenMeunBtn, ui_event_OpenMeunBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AdminView, ui_event_AdminView, LV_EVENT_ALL, NULL);

}
