// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_LoginView_screen_init(void)
{
    ui_LoginView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_LoginView, &ui_img_loginback_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_tiled(ui_LoginView, true, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_LoginView);
    lv_obj_set_width(ui_Keyboard1, 1020);
    lv_obj_set_height(ui_Keyboard1, 274);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 160);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_Keyboard1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_LoginBlock = lv_obj_create(ui_LoginView);
    lv_obj_set_width(ui_LoginBlock, 414);
    lv_obj_set_height(ui_LoginBlock, 513);
    lv_obj_set_x(ui_LoginBlock, 0);
    lv_obj_set_y(ui_LoginBlock, -1);
    lv_obj_set_align(ui_LoginBlock, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LoginBlock, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LoginBlock, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LoginBlock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoginBlock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoginBlock, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoginBlock, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoginHead = lv_obj_create(ui_LoginBlock);
    lv_obj_remove_style_all(ui_LoginHead);
    lv_obj_set_height(ui_LoginHead, 59);
    lv_obj_set_width(ui_LoginHead, lv_pct(100));
    lv_obj_set_x(ui_LoginHead, -86);
    lv_obj_set_y(ui_LoginHead, -185);
    lv_obj_set_align(ui_LoginHead, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LoginHead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loginTitleText = lv_label_create(ui_LoginHead);
    lv_obj_set_width(ui_loginTitleText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loginTitleText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loginTitleText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loginTitleText, "登录");
    lv_obj_set_style_text_font(ui_loginTitleText, &ui_font_harmonyOSTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_usernameText = lv_label_create(ui_LoginBlock);
    lv_obj_set_width(ui_usernameText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_usernameText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_usernameText, -25);
    lv_obj_set_y(ui_usernameText, -145);
    lv_obj_set_align(ui_usernameText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_usernameText, "账号");
    lv_obj_add_flag(ui_usernameText, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags

    ui_inusername = lv_textarea_create(ui_LoginBlock);
    lv_obj_set_width(ui_inusername, lv_pct(100));
    lv_obj_set_height(ui_inusername, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_inusername, 77);
    lv_obj_set_y(ui_inusername, -85);
    lv_obj_set_align(ui_inusername, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_inusername, "user...");
    lv_textarea_set_one_line(ui_inusername, true);



    ui_passwordText = lv_label_create(ui_LoginBlock);
    lv_obj_set_width(ui_passwordText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_passwordText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_passwordText, -192);
    lv_obj_set_y(ui_passwordText, -78);
    lv_obj_set_align(ui_passwordText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_passwordText, "密码");

    ui_inpassword = lv_textarea_create(ui_LoginBlock);
    lv_obj_set_width(ui_inpassword, lv_pct(100));
    lv_obj_set_height(ui_inpassword, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_inpassword, -45);
    lv_obj_set_y(ui_inpassword, -37);
    lv_obj_set_align(ui_inpassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_inpassword, "adbcefg....");
    lv_textarea_set_one_line(ui_inpassword, true);
    lv_textarea_set_password_mode(ui_inpassword, true);
    lv_obj_add_flag(ui_inpassword, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_inpassword, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags

    lv_obj_set_style_text_font(ui_inpassword, &ui_font_harmonyOS, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_topasswordText = lv_label_create(ui_LoginBlock);
    lv_obj_set_width(ui_topasswordText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_topasswordText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_topasswordText, -192);
    lv_obj_set_y(ui_topasswordText, -78);
    lv_obj_set_align(ui_topasswordText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_topasswordText, "再输入一次密码");
    lv_obj_add_flag(ui_topasswordText, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_intopassword = lv_textarea_create(ui_LoginBlock);
    lv_obj_set_width(ui_intopassword, lv_pct(100));
    lv_obj_set_height(ui_intopassword, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_intopassword, -45);
    lv_obj_set_y(ui_intopassword, -37);
    lv_obj_set_align(ui_intopassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_intopassword, "abcdefg.....");
    lv_textarea_set_one_line(ui_intopassword, true);
    lv_textarea_set_password_mode(ui_intopassword, true);
    lv_obj_add_flag(ui_intopassword, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_intopassword, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags

    lv_obj_set_style_text_font(ui_intopassword, &ui_font_harmonyOS, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_LoginBlock);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 106);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RegButton = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_RegButton, 100);
    lv_obj_set_height(ui_RegButton, 50);
    lv_obj_set_align(ui_RegButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_RegButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RegButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RegButton, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_RegButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "注册");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIR001 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_AIR001);
    lv_obj_set_width(ui_AIR001, 98);
    lv_obj_set_height(ui_AIR001, 50);
    lv_obj_set_align(ui_AIR001, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIR001, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoginButton = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_LoginButton, 100);
    lv_obj_set_height(ui_LoginButton, 50);
    lv_obj_set_align(ui_LoginButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LoginButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_LoginButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "登录");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_LoginBlock);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 373);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, -135);
    lv_obj_set_y(ui_Container1, 199);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button1, 171);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "直接点菜");

    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inusername, ui_event_inusername, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_inpassword, ui_event_inpassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_intopassword, ui_event_intopassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RegButton, ui_event_RegButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginButton, ui_event_LoginButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LoginView, ui_event_LoginView, LV_EVENT_ALL, NULL);

}
