// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../UI/ui_events.h"
#include "../UI/ui.h"
#include <stdio.h>
#include "Model.h"
extern bool setUserType(int uid,int type);
extern bool delUser(int uid);
extern Ulist userhead;
static int deluid = 0;
int tempadmin[1024] = {[0 ... 1023] = 0};
void userlistInit();
void createUserItme(char name[],int uid,int type);
static void Dropdown_event_handler(lv_event_t * e);
static void Save_event_handler(lv_event_t * e);
static void msgbox_event_cb(lv_event_t * e);
static void Del_event_handler(lv_event_t * e);
//页面初始化
void viewAdminInit(lv_event_t * e)
{
    printf("初始化管理页面\n");
    userlistInit();

}
void userlistInit()
{
    lv_obj_clean(ui_UserListBody);
    Ulist p=NULL,n=NULL;
    //从头结点到末尾进行遍历  安全遍历
    list_for_each_entry_safe(p,n,&(userhead->my),my)
    {
        createUserItme(p->data.data.name,p->data.data.uid,p->data.data.type);
    }
}
void createUserItme(char name[],int uid,int type) //渲染一个用户列表
{
    char buf[10] = {0};
    sprintf(buf,"%d",uid);
    lv_obj_t *temp_UserListItem = lv_obj_create(ui_UserListBody);
    lv_obj_remove_style_all(temp_UserListItem);
    lv_obj_set_width(temp_UserListItem, 531);
    lv_obj_set_height(temp_UserListItem, 50);
    lv_obj_set_x(temp_UserListItem, 0);
    lv_obj_set_y(temp_UserListItem, -2);
    lv_obj_set_align(temp_UserListItem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(temp_UserListItem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(temp_UserListItem, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(temp_UserListItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t *temp_Label2 = lv_label_create(temp_UserListItem);
    lv_obj_set_width(temp_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(temp_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(temp_Label2, name);

    lv_obj_t *temp_Dropdown1 = lv_dropdown_create(temp_UserListItem);
    lv_dropdown_set_options(temp_Dropdown1, "普通客户\nVIP客户\n管理员\n封禁");
    lv_obj_set_width(temp_Dropdown1, 150);
    lv_obj_set_height(temp_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(temp_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(temp_Dropdown1, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(temp_Dropdown1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(temp_Dropdown1), &ui_font_harmonyOS,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *temp_operation = lv_obj_create(temp_UserListItem);
    lv_obj_remove_style_all(temp_operation);
    lv_obj_set_width(temp_operation, 117);
    lv_obj_set_height(temp_operation, 50);
    lv_obj_set_align(temp_operation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(temp_operation, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(temp_operation, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(temp_operation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t *temp_saveBtn = lv_btn_create(temp_operation);
    lv_obj_set_width(temp_saveBtn, 55);
    lv_obj_set_height(temp_saveBtn, 40);
    lv_obj_set_align(temp_saveBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(temp_saveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(temp_saveBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(temp_saveBtn, lv_color_hex(0x82B7F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(temp_saveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *temp_saveBtnText = lv_label_create(temp_saveBtn);
    lv_obj_set_width(temp_saveBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(temp_saveBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_saveBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(temp_saveBtnText, "保存");
    lv_obj_set_style_text_font(temp_saveBtnText, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *temp_userListUid = lv_label_create(temp_saveBtn);
    lv_obj_set_width(temp_userListUid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(temp_userListUid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_userListUid, LV_ALIGN_CENTER);
    lv_label_set_text(temp_userListUid, buf);
    lv_obj_add_flag(temp_userListUid, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_t *temp_delBtn = lv_btn_create(temp_operation);
    lv_obj_set_width(temp_delBtn, 55);
    lv_obj_set_height(temp_delBtn, 40);
    lv_obj_set_align(temp_delBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(temp_delBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(temp_delBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(temp_delBtn, lv_color_hex(0x82B7F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(temp_delBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *temp_delBtnText = lv_label_create(temp_delBtn);
    lv_obj_set_width(temp_delBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(temp_delBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_delBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(temp_delBtnText, "删除");
    lv_obj_set_style_text_font(temp_delBtnText, &ui_font_harmonyOS, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *temp_delListUid = lv_label_create(temp_delBtn);
    lv_obj_set_width(temp_delListUid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(temp_delListUid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_delListUid, LV_ALIGN_CENTER);
    lv_label_set_text(temp_delListUid, buf);
    lv_obj_add_flag(temp_delListUid, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_t *temp_delListUid1 = lv_label_create(temp_Dropdown1);
    lv_obj_set_width(temp_delListUid1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(temp_delListUid1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(temp_delListUid1, LV_ALIGN_CENTER);
    lv_label_set_text(temp_delListUid1, buf);
    lv_obj_add_flag(temp_delListUid1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_dropdown_set_selected(temp_Dropdown1,type==-1?3:type);
    lv_obj_add_event_cb(temp_Dropdown1, Dropdown_event_handler, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(temp_saveBtn, Save_event_handler, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(temp_delBtn, Del_event_handler, LV_EVENT_ALL, NULL);
}

static void Dropdown_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        char buf[32];
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
        printf("Option: %s\n", buf);
        int type = 0;
        if(strcmp(buf,"管理员")==0)type=2;
        if(strcmp(buf,"VIP客户")==0)type=1;
        if(strcmp(buf,"封禁")==0)type=-1;
        // 遍历 target 的所有子对象
        uint32_t child_cnt = lv_obj_get_child_cnt(obj);
        for (uint32_t i = 0; i < child_cnt; i++) {
            lv_obj_t * child = lv_obj_get_child(obj, i);
            // 检查该子对象是否是 label
            if (lv_obj_check_type(child, &lv_label_class)) {
                // 找到了 label！
                const char * uid_str = lv_label_get_text(child);
                printf("Label text: %s\n", uid_str);
                // if(strcmp(uid_str,"-")==0)continue;
                int uid = atoi(uid_str);
                // setUserType(uid,type);
                tempadmin[uid] = type;
                printf("%d = %d",uid,type);
                break; 
            }
        }
        
    }
}
static void Save_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_CLICKED) {
        char buf[32];
        // 遍历 target 的所有子对象
        uint32_t child_cnt = lv_obj_get_child_cnt(obj);
        for (uint32_t i = 0; i < child_cnt; i++) {
            lv_obj_t * child = lv_obj_get_child(obj, i);
            // 检查该子对象是否是 label
            if (lv_obj_check_type(child, &lv_label_class)) {
                // 找到了 label！
                const char * uid_str = lv_label_get_text(child);
                printf("Label text: %s\n", uid_str);
                if(strcmp(uid_str,"保存")==0)continue;
                int uid = atoi(uid_str);
                if(setUserType(uid,tempadmin[uid]))
                {
                    lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "保存成功！", NULL, true);
                    lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
                    lv_obj_center(mbox1);
                    userlistInit();
                }
                // tempadmin[uid] = type;
                break; 
            }
        }
        
    }
}
static void msgbox_event_cb(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_current_target(e);
    char buf[20] ;
    sprintf(buf,"%s", lv_msgbox_get_active_btn_text(obj));
    if(strcmp(buf,"确认")==0){
        delUser(deluid);
        lv_msgbox_close(obj);
        userlistInit();
    }
    if(strcmp(buf,"取消")==0){
        lv_msgbox_close(obj);
    }
}
static void Del_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_CLICKED) {
        char buf[32];
        // 遍历 target 的所有子对象
        uint32_t child_cnt = lv_obj_get_child_cnt(obj);
        for (uint32_t i = 0; i < child_cnt; i++) {
            lv_obj_t * child = lv_obj_get_child(obj, i);
            // 检查该子对象是否是 label
            if (lv_obj_check_type(child, &lv_label_class)) {
                // 找到了 label！
                const char * uid_str = lv_label_get_text(child);
                printf("Label text: %s\n", uid_str);
                if(strcmp(uid_str,"删除")==0)continue;
                int uid = atoi(uid_str);
                deluid = uid;
                static const char * btns[] ={"确认", "取消", ""};
                lv_obj_t * mbox1 = lv_msgbox_create(NULL, "警告", "你确认要删除该用户吗，这是不可回溯的.", btns, false);
                lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
                lv_obj_add_event_cb(mbox1, msgbox_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
                lv_obj_center(mbox1);
                
                break; 
            }
        }
        
    }
}