// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../UI/ui_events.h"
#include "../UI/ui.h"
#include <stdio.h>
bool Login_type = true;
void reg_ac_ev(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
	
	lv_obj_set_style_bg_color(ta,lv_color_hex(0x2196F3),LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_LoginButton,lv_color_hex(0xB3B3B3),LV_STATE_DEFAULT);

	if(Login_type){
		Login_type = false;
		lv_label_set_text(ui_loginTitleText,"注册");
		lv_textarea_set_text(ui_inusername,"");
		lv_textarea_set_text(ui_inpassword,"");
		lv_textarea_set_text(ui_intopassword,"");
	}
	else
	{
		//注册逻辑
		printf("执行注册逻辑");
		const char *user = lv_textarea_get_text(ui_inusername);
        const char *pass = lv_textarea_get_text(ui_inpassword);
        const char *topass = lv_textarea_get_text(ui_intopassword);
        if(strcmp(user,"")==0||strcmp(pass,"")==0){
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "账号或密码为空", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
            return;
        }
        if(strcmp(pass,topass)!=0){
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "2次密码不一样！", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
            return;
        }
        if(regMenu(user,pass)){
            printf("注册成功！");
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "注册成功！", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
            // lv_obj_add_flag(superior, LV_OBJ_FLAG_HIDDEN);
            // login_main_meun();


        }else{
            printf("注册失败！");
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "注册失败！", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
        }
	}
}
void login_ac_ev(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
	
	lv_obj_set_style_bg_color(ta,lv_color_hex(0x2196F3),LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_RegButton,lv_color_hex(0xB3B3B3),LV_STATE_DEFAULT);

	if(Login_type){
		//登录逻辑
		printf("执行登录逻辑");
		const char *user = lv_textarea_get_text(ui_inusername);
        const char *pass = lv_textarea_get_text(ui_inpassword);
        if(strcmp(user,"")==0||strcmp(pass,"")==0){
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "账号或密码为空", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
            return;
        }
        if(loginMenu(user,pass)!=-1){
            printf("登录成功！");
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "登录成功！", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
            // lv_obj_add_flag(superior, LV_OBJ_FLAG_HIDDEN);

        }else{
            printf("登录失败！");
            lv_obj_t * mbox1 = lv_msgbox_create(NULL, "提示", "登录失败！", NULL, true);
            lv_obj_set_style_text_font(mbox1,&ui_font_harmonyOS,0);
            lv_obj_center(mbox1);
        }
	}
	else
	{
		Login_type = true;
		lv_label_set_text(ui_loginTitleText,"登录");
		lv_textarea_set_text(ui_inusername,"");
		lv_textarea_set_text(ui_inpassword,"");
		lv_textarea_set_text(ui_intopassword,"");
	}
}
void set_kbindex_ev(lv_event_t * e)
{
	// lv_event_code_t code = lv_event_get_code(e);
    // lv_obj_t * ta = lv_event_get_target(e);

	lv_obj_move_foreground(ui_Keyboard1);
}