// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void board_Animation(lv_obj_t * TargetObject, int delay);
void boardbay_Animation(lv_obj_t * TargetObject, int delay);
void loading_Animation(lv_obj_t * TargetObject, int delay);
void yuanloading_Animation(lv_obj_t * TargetObject, int delay);
void yuanloading2_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_HelloView
void ui_HelloView_screen_init(void);
void ui_event_HelloView(lv_event_t * e);
lv_obj_t * ui_HelloView;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label8;


// SCREEN: ui_LoginView
void ui_LoginView_screen_init(void);
void ui_event_LoginView(lv_event_t * e);
lv_obj_t * ui_LoginView;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_LoginBlock;
lv_obj_t * ui_LoginHead;
lv_obj_t * ui_loginTitleText;
lv_obj_t * ui_usernameText;
void ui_event_inusername(lv_event_t * e);
lv_obj_t * ui_inusername;
lv_obj_t * ui_passwordText;
void ui_event_inpassword(lv_event_t * e);
lv_obj_t * ui_inpassword;
lv_obj_t * ui_topasswordText;
void ui_event_intopassword(lv_event_t * e);
lv_obj_t * ui_intopassword;
lv_obj_t * ui_Container3;
void ui_event_RegButton(lv_event_t * e);
lv_obj_t * ui_RegButton;
lv_obj_t * ui_Label1;
lv_obj_t * ui_AIR001;
void ui_event_LoginButton(lv_event_t * e);
lv_obj_t * ui_LoginButton;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label3;


// SCREEN: ui_MenuView
void ui_MenuView_screen_init(void);
void ui_event_MenuView(lv_event_t * e);
lv_obj_t * ui_MenuView;
lv_obj_t * ui_Menu;
lv_obj_t * ui_meunItem1;
void ui_event_menuButton1(lv_event_t * e);
lv_obj_t * ui_menuButton1;
lv_obj_t * ui_meunimg1;
lv_obj_t * ui_meunUid1;
lv_obj_t * ui_meuntext1;
lv_obj_t * ui_meunItem2;
void ui_event_menuButton2(lv_event_t * e);
lv_obj_t * ui_menuButton2;
lv_obj_t * ui_meunimg2;
lv_obj_t * ui_meunUid2;
lv_obj_t * ui_meuntext2;
lv_obj_t * ui_meunItem3;
void ui_event_menuButton3(lv_event_t * e);
lv_obj_t * ui_menuButton3;
lv_obj_t * ui_meunimg3;
lv_obj_t * ui_meunUid3;
lv_obj_t * ui_meuntext3;
lv_obj_t * ui_meunItem4;
void ui_event_menuButton4(lv_event_t * e);
lv_obj_t * ui_menuButton4;
lv_obj_t * ui_meunimg4;
lv_obj_t * ui_meunUid4;
lv_obj_t * ui_meuntext4;
lv_obj_t * ui_meunItem5;
void ui_event_menuButton5(lv_event_t * e);
lv_obj_t * ui_menuButton5;
lv_obj_t * ui_meunimg5;
lv_obj_t * ui_meunUid5;
lv_obj_t * ui_meuntext5;
lv_obj_t * ui_meunItem6;
void ui_event_menuButton6(lv_event_t * e);
lv_obj_t * ui_menuButton6;
lv_obj_t * ui_meunimg6;
lv_obj_t * ui_meunUid6;
lv_obj_t * ui_meuntext6;
lv_obj_t * ui_meunItem7;
void ui_event_menuButton7(lv_event_t * e);
lv_obj_t * ui_menuButton7;
lv_obj_t * ui_meunimg7;
lv_obj_t * ui_meunUid7;
lv_obj_t * ui_meuntext7;
lv_obj_t * ui_meunItem8;
void ui_event_menuButton8(lv_event_t * e);
lv_obj_t * ui_menuButton8;
lv_obj_t * ui_meunimg8;
lv_obj_t * ui_meunUid8;
lv_obj_t * ui_meuntext8;
lv_obj_t * ui_PagesInfo;
lv_obj_t * ui_Bill;
void ui_event_OutLoginBtn(lv_event_t * e);
lv_obj_t * ui_OutLoginBtn;
lv_obj_t * ui_OutLoginText;
void ui_event_OpenAdminBtn(lv_event_t * e);
lv_obj_t * ui_OpenAdminBtn;
lv_obj_t * ui_OpenAdminBtnText;
lv_obj_t * ui_Loading;


// SCREEN: ui_AdminView
void ui_AdminView_screen_init(void);
void ui_event_AdminView(lv_event_t * e);
lv_obj_t * ui_AdminView;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_UserListHead;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_UserListBody;
lv_obj_t * ui_UserListItem;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_operation;
lv_obj_t * ui_saveBtn;
lv_obj_t * ui_saveBtnText;
lv_obj_t * ui_userListUid;
lv_obj_t * ui_delBtn;
lv_obj_t * ui_delBtnText;
lv_obj_t * ui_delListUid;
void ui_event_OpenMeunBtn(lv_event_t * e);
lv_obj_t * ui_OpenMeunBtn;
lv_obj_t * ui_OpenMeunBtnText;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void board_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 500, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void boardbay_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -500, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}
void loading_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 3000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -1000, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void yuanloading_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 5000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 0, 610);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 1);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 3000);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}
void yuanloading2_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 610, 650);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 8000);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_HelloView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        yuanloading_Animation(ui_Container2, 0);
        OpenLoginView(e);
        yuanloading2_Animation(ui_Container2, 0);
    }
}
void ui_event_LoginView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CANCEL) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_inusername(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_inusername);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        set_kbindex_ev(e);
    }
}
void ui_event_inpassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_inpassword);
        set_kbindex_ev(e);
    }
}
void ui_event_intopassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_intopassword);
        set_kbindex_ev(e);
    }
}
void ui_event_RegButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        reg_ac_ev(e);
        _ui_flag_modify(ui_intopassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_topasswordText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_LoginButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        login_ac_ev(e);
        _ui_flag_modify(ui_intopassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_topasswordText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        anonymouslogin(e);
    }
}
void ui_event_MenuView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        board_Animation(ui_Bill, 0);
        _ui_basic_set_property(ui_Bill, _UI_BASIC_PROPERTY_POSITION_Y,  46);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        boardbay_Animation(ui_Bill, 0);
        _ui_basic_set_property(ui_Bill, _UI_BASIC_PROPERTY_POSITION_Y,  460);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        viewNextPage(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        viewLaftPage(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        viewMenuInit(e);
    }
}
void ui_event_menuButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_menuButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        viewAddChopp(e);
    }
}
void ui_event_OutLoginBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        viewOutLogin(e);
        _ui_screen_change(&ui_LoginView, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_LoginView_screen_init);
    }
}
void ui_event_OpenAdminBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AdminView, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_AdminView_screen_init);
    }
}
void ui_event_AdminView(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        viewAdminInit(e);
    }
}
void ui_event_OpenMeunBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuView, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_MenuView_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HelloView_screen_init();
    ui_LoginView_screen_init();
    ui_MenuView_screen_init();
    ui_AdminView_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HelloView);
}
