// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_LoginView;
extern lv_obj_t * ui_LoginHead;
extern lv_obj_t * ui_loginTitleText;
extern lv_obj_t * ui_usernameText;
void ui_event_inusername(lv_event_t * e);
extern lv_obj_t * ui_inusername;
extern lv_obj_t * ui_passwordText;
void ui_event_inpassword(lv_event_t * e);
extern lv_obj_t * ui_inpassword;
extern lv_obj_t * ui_topasswordText;
void ui_event_intopassword(lv_event_t * e);
extern lv_obj_t * ui_intopassword;
extern lv_obj_t * ui_Container3;
void ui_event_RegButton(lv_event_t * e);
extern lv_obj_t * ui_RegButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_AIR001;
void ui_event_LoginButton(lv_event_t * e);
extern lv_obj_t * ui_LoginButton;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_ylnimg_png);    // assets/ylnimg.png



LV_FONT_DECLARE(ui_font_harmonyOS);
LV_FONT_DECLARE(ui_font_harmonyOSTitle);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
