// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void board_Animation(lv_obj_t * TargetObject, int delay);
void boardbay_Animation(lv_obj_t * TargetObject, int delay);
void loading_Animation(lv_obj_t * TargetObject, int delay);
void yuanloading_Animation(lv_obj_t * TargetObject, int delay);
void yuanloading2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_HelloView
void ui_HelloView_screen_init(void);
void ui_event_HelloView(lv_event_t * e);
extern lv_obj_t * ui_HelloView;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label8;
// SCREEN: ui_LoginView
void ui_LoginView_screen_init(void);
void ui_event_LoginView(lv_event_t * e);
extern lv_obj_t * ui_LoginView;
void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_LoginBlock;
extern lv_obj_t * ui_LoginHead;
extern lv_obj_t * ui_loginTitleText;
extern lv_obj_t * ui_usernameText;
void ui_event_inusername(lv_event_t * e);
extern lv_obj_t * ui_inusername;
extern lv_obj_t * ui_passwordText;
void ui_event_inpassword(lv_event_t * e);
extern lv_obj_t * ui_inpassword;
extern lv_obj_t * ui_topasswordText;
void ui_event_intopassword(lv_event_t * e);
extern lv_obj_t * ui_intopassword;
extern lv_obj_t * ui_Container3;
void ui_event_RegButton(lv_event_t * e);
extern lv_obj_t * ui_RegButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_AIR001;
void ui_event_LoginButton(lv_event_t * e);
extern lv_obj_t * ui_LoginButton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_MenuView
void ui_MenuView_screen_init(void);
void ui_event_MenuView(lv_event_t * e);
extern lv_obj_t * ui_MenuView;
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_meunItem1;
void ui_event_menuButton1(lv_event_t * e);
extern lv_obj_t * ui_menuButton1;
extern lv_obj_t * ui_meunimg1;
extern lv_obj_t * ui_meunUid1;
extern lv_obj_t * ui_meuntext1;
extern lv_obj_t * ui_meunItem2;
void ui_event_menuButton2(lv_event_t * e);
extern lv_obj_t * ui_menuButton2;
extern lv_obj_t * ui_meunimg2;
extern lv_obj_t * ui_meunUid2;
extern lv_obj_t * ui_meuntext2;
extern lv_obj_t * ui_meunItem3;
void ui_event_menuButton3(lv_event_t * e);
extern lv_obj_t * ui_menuButton3;
extern lv_obj_t * ui_meunimg3;
extern lv_obj_t * ui_meunUid3;
extern lv_obj_t * ui_meuntext3;
extern lv_obj_t * ui_meunItem4;
void ui_event_menuButton4(lv_event_t * e);
extern lv_obj_t * ui_menuButton4;
extern lv_obj_t * ui_meunimg4;
extern lv_obj_t * ui_meunUid4;
extern lv_obj_t * ui_meuntext4;
extern lv_obj_t * ui_meunItem5;
void ui_event_menuButton5(lv_event_t * e);
extern lv_obj_t * ui_menuButton5;
extern lv_obj_t * ui_meunimg5;
extern lv_obj_t * ui_meunUid5;
extern lv_obj_t * ui_meuntext5;
extern lv_obj_t * ui_meunItem6;
void ui_event_menuButton6(lv_event_t * e);
extern lv_obj_t * ui_menuButton6;
extern lv_obj_t * ui_meunimg6;
extern lv_obj_t * ui_meunUid6;
extern lv_obj_t * ui_meuntext6;
extern lv_obj_t * ui_meunItem7;
void ui_event_menuButton7(lv_event_t * e);
extern lv_obj_t * ui_menuButton7;
extern lv_obj_t * ui_meunimg7;
extern lv_obj_t * ui_meunUid7;
extern lv_obj_t * ui_meuntext7;
extern lv_obj_t * ui_meunItem8;
void ui_event_menuButton8(lv_event_t * e);
extern lv_obj_t * ui_menuButton8;
extern lv_obj_t * ui_meunimg8;
extern lv_obj_t * ui_meunUid8;
extern lv_obj_t * ui_meuntext8;
extern lv_obj_t * ui_PagesInfo;
extern lv_obj_t * ui_Bill;
void ui_event_OutLoginBtn(lv_event_t * e);
extern lv_obj_t * ui_OutLoginBtn;
extern lv_obj_t * ui_OutLoginText;
void ui_event_OpenAdminBtn(lv_event_t * e);
extern lv_obj_t * ui_OpenAdminBtn;
extern lv_obj_t * ui_OpenAdminBtnText;
extern lv_obj_t * ui_Loading;
void ui_event_Info(lv_event_t * e);
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_infoImage;
extern lv_obj_t * ui_infoName;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Container7;
void ui_event_infobackbtn(lv_event_t * e);
extern lv_obj_t * ui_infobackbtn;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_infomsg;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label9;
void ui_event_EditCoinTextArea(lv_event_t * e);
extern lv_obj_t * ui_EditCoinTextArea;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_infoUid;
extern lv_obj_t * ui_infoBtnText;
extern lv_obj_t * ui_Keyboard2;
// SCREEN: ui_AdminView
void ui_AdminView_screen_init(void);
void ui_event_AdminView(lv_event_t * e);
extern lv_obj_t * ui_AdminView;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_UserListHead;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_UserListBody;
extern lv_obj_t * ui_UserListItem;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_operation;
extern lv_obj_t * ui_saveBtn;
extern lv_obj_t * ui_saveBtnText;
extern lv_obj_t * ui_userListUid;
extern lv_obj_t * ui_delBtn;
extern lv_obj_t * ui_delBtnText;
extern lv_obj_t * ui_delListUid;
void ui_event_OpenMeunBtn(lv_event_t * e);
extern lv_obj_t * ui_OpenMeunBtn;
extern lv_obj_t * ui_OpenMeunBtnText;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_loginback_png);    // assets/loginback.png
LV_IMG_DECLARE(ui_img_yuanloading_png);    // assets/yuanloading.png
LV_IMG_DECLARE(ui_img_1371183408);    // assets/背景.png
LV_IMG_DECLARE(ui_img_xtq_img_png);    // assets/xtq_img.png
LV_IMG_DECLARE(ui_img_caipinginfo_png);    // assets/caipinginfo.png



LV_FONT_DECLARE(ui_font_harmonyOS);
LV_FONT_DECLARE(ui_font_harmonyOSTitle);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
