// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
#include "ui.h"
void OpenLoginView(lv_event_t * e);
void filesinit(lv_event_t * e);
void set_kbindex_ev(lv_event_t * e);
void reg_ac_ev(lv_event_t * e);
void login_ac_ev(lv_event_t * e);
void anonymouslogin(lv_event_t * e);
void viewNextPage(lv_event_t * e);
void viewLaftPage(lv_event_t * e);
void viewMenuInit(lv_event_t * e);
void viewAddChopp(lv_event_t * e);
void viewAddInfo(lv_event_t * e);
void viewOutLogin(lv_event_t * e);
void infoBtnac(lv_event_t * e);
void viewAdminInit(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
